### PR TITLE
update cats effect to v3

### PR DESCRIPTION
**Pull request by gipeshka**

### CODE REVIEW

**Review by chuwy — CHANGES_REQUESTED** [review]
Hi @gipeshka! Thanks for your interest in scala-lru-map! Unfortunatelly, I don't think this bump would work out as the other core dependency [scalacache](https://github.com/cb372/scalacache) still on CE2 and these major versions are neither source or binary compatible.

**Comment by gipeshka** [comment]
Hm, I guess it should've failed during compilation. I was able to run tests and those were passing.

Though you might be right, feel free to close this one.

**Comment by chuwy** [comment]
Yeah, I guess we use just very small subset of Cats Effect in the library, which hasn't caused any errors. But if someone brings both dependencies into their project - it would likely fail either runtime or compiletime.

**Comment by chuwy** [comment]
Closing in favor of https://github.com/snowplow-incubator/scala-lru-map/pull/47

**Pull request closed without merging**
