### PR TITLE
Release 0.1.0

### PR DESCRIPTION
**Pull request by three**
I think this is why the deploy script is failing: https://travis-ci.org/snowplow-incubator/scala-lru-map/jobs/396398432

### CODE REVIEW

**Review by BenFradet — APPROVED** [review]
you can retag here no need to merge

**Comment by BenFradet** [comment]
@three  can you remove the commit bumping the version, merge, squash and release (ping me when you want to release I'll check everything is in place)

**Comment by three** [comment]
@BenFradet Should I merge into master?

**Comment by BenFradet** [comment]
yes since you've already merged to master a few prs ago

**Comment by three** [comment]
I think it's ready to release. Should I add the 0.1.0 tag?

**Pull request merged**
